// <auto-generated />
using System;
using Contratos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contratos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContratosDbContext))]
    [Migration("20260929165753_InicialContratos")]
    partial class InicialContratos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Contratos.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivoDocx")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivoPdf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataContrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailDestinatario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailEnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailErroMensagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualHonorarios")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusEmail")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusWhatsapp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsappDestinatario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WhatsappEnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsappErroMensagem")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj");

                    b.HasIndex("Status");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Contratos.Domain.Entities.ContratoResponsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContratoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("ContratoResponsaveis");
                });

            modelBuilder.Entity("Contratos.Domain.Entities.EventoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContratoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("EventosHistorico");
                });

            modelBuilder.Entity("Contratos.Domain.Entities.ContratoResponsavel", b =>
                {
                    b.HasOne("Contratos.Domain.Entities.Contrato", null)
                        .WithMany("Responsaveis")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contratos.Domain.Entities.EventoHistorico", b =>
                {
                    b.HasOne("Contratos.Domain.Entities.Contrato", null)
                        .WithMany("Historico")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contratos.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Responsaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
